import { Car } from "@/schemas";

export const cars: Car[] = [
  {
    id: 1,
    brand: "Toyota",
    name: "Corolla",
    year: 2020,
    fuel: "Gasoline",
    km: "10,000",
    color: "White",
    priceTf: 20000,
    price: 18000,
    description: "A reliable car in excellent condition.",
    coverImage: "https://example.com/toyota-corolla-cover.jpg",
    firstImage: "https://example.com/toyota-corolla-1.jpg",
    secondImage: "https://example.com/toyota-corolla-2.jpg",
    thirdImage: "https://example.com/toyota-corolla-3.jpg",
    fourthImage: null,
    fifthImage: null,
    sixthImage: null,
    published: true,
    userId: "user123",
  },
  {
    id: 2,
    brand: "Honda",
    name: "Civic",
    year: 2019,
    fuel: "Gasoline",
    km: "15,000",
    color: "Black",
    priceTf: 19000,
    price: 17000,
    description: "A sporty car in great condition.",
    coverImage: "https://example.com/honda-civic-cover.jpg",
    firstImage: "https://example.com/honda-civic-1.jpg",
    secondImage: "https://example.com/honda-civic-2.jpg",
    thirdImage: "https://example.com/honda-civic-3.jpg",
    fourthImage: null,
    fifthImage: null,
    sixthImage: null,
    published: false,
    userId: "user456",
  },
  {
    id: 3,
    brand: "Ford",
    name: "Focus",
    year: 2018,
    fuel: "Gasoline",
    km: "20,000",
    color: "Blue",
    priceTf: 18000,
    price: 16000,
    description: "A practical car in good condition.",
    coverImage: "https://example.com/ford-focus-cover.jpg",
    firstImage: "https://example.com/ford-focus-1.jpg",
    secondImage: "https://example.com/ford-focus-2.jpg",
    thirdImage: null,
    fourthImage: null,
    fifthImage: null,
    sixthImage: null,
    published: true,
    userId: "user789",
  },
];
